### PR TITLE
Rig for auto-start with `systemd`

### PR DESCRIPTION
**Pull request by tomgidden**
I'm not sure I've done this right, being a `systemd` novice, but it works for me on my headless Pi-based setup.

This one's less of a slam-dunk. I won't be offended if you decline this PR!  ;)

### CODE REVIEW

**Comment by gfwilliams** [comment]
Sorry for the delay... 

Looks good - any chance of changing the path from `/home/node-red` to `/home/pi`, or adding a comment about paths? I think `pi` is what most people would have if they used the instructions.

**Comment by tomgidden** [comment]
Hmm.. that's true.  There is a note in there about paths already:
> and edit it as necessary to match your installation directory and user configuration.

but who reads documentation anyway? :wink:

It looks like the service name might be different too.. It appears to be `nodered` rather than `Node-RED`.  I don't have a "blank" Raspbian Pi handy to check at the moment.  I'll commit that separately.

**Comment by gfwilliams** [comment]
Sorry, I must have missed that when I glossed over. Thanks for humouring me :)

I'm not 100% sure on the node red service or how it gets started - my pi with it installed doesn't list it with `sudo service --status-all` or in `init.d`, but it does appear to be started?

**Comment by tomgidden** [comment]
The `nodered.service` file is installed as part of the install procedure written at the top of this repo's `README.md`;  `sudo systemctl start nodered.service` is what gets it going, and `sudo systemctl enable nodered.service`

Honestly, I'm not sure how `service` and `systemctl` interact. `init.d` is legacy, it seems, in favour of `/etc/systemd`. Apparently `systemctl` is controversially "not very UNIXy", but it seems to be what Debian's going with, so if you can't beat 'em…

**Pull request merged**
