### PR TITLE
config by Device

### PR DESCRIPTION
**Pull request by G1K**
fix mqtt discovery Home Assistant prefix
fix read device services

### CODE REVIEW

**Comment by gfwilliams** [comment]
Hi - please can you let me know when you're ready to merge with this?

What's the reasoning behind the removal of `discovery.stopScan` in `connect.js`? I'm just conscious that I put a bunch of work into that recently (I believe around that area) to actually fix some issues with repeated connections (specifically via `localhost/ide`), and I'd hate to see it broken again

**Comment by G1K** [comment]
So far I opened this PR just to check the code.

discovery.stopScan I will return it back, while there is no examination, but it seems there was a freeze or stopped scanning.

Controversial points that I would like to discuss.
temp / temperature - is it fundamentally? and I need to redo the parser so that it returns the temp


The topic ble prefix for mqtt disocvery, I corrected the nesting. I need it to run multiple gateways with one mqtt server. Perhaps it is worth considering the format of the template in the config.


And you need to supplement the documentation with the ability to configure device settings.

**Comment by gfwilliams** [comment]
> discovery.stopScan ... but it seems there was a freeze or stopped scanning.

Ok, that's possible. But in that case it's probably because an error wasn't handled somewhere in connect and `startScan` was never called.

Some (many?) bluetooth adaptors won't connect while scanning is in progress - so the `stopScan` is definitely needed before any connection starts for most people (even if it's not for you).

> temp / temperature - is it fundamentally? and I need to redo the parser so that it returns the temp

Do you have a link to the code you mean? I'm not sure I understand.

> The topic ble prefix for mqtt disocvery, I corrected the nesting. I need it to run multiple gateways with one mqtt server. Perhaps it is worth considering the format of the template in the config.

Again, I'm not sure I understand here?

> And you need to supplement the documentation with the ability to configure device settings.

You mean the code that you've just added? You might have noticed but I already added documentation to the config file for the previous homeassistant commit.

However if you're adding the changes, you're in a much better position to document them than me!

**Comment by G1K** [comment]
@gfwilliams Please check it out.
Parsing of xiaomi devices with encryption I will add the following PR tk it uses the device settings

**Comment by G1K** [comment]
@gfwilliams Please check it

**Comment by gfwilliams** [comment]
Thanks - I've been on holiday these last two weeks (still am) but when I return I'll definitely check this out

**Comment by gfwilliams** [comment]
Ok, back now - this looks good, but please could you add some docs to the extra fields in the config.json file?

In known_devices:

* "presence_timeout" : 1,
*  "min_rssi" : -80,
* "bind_key": "",
* "model": "",
* "cache_state": false

And:

* "exclude_services"
* "exclude_attributes"

It seems like probably a few of these aren't actually used for anything at the moment? If so it'd be an idea to mention so it's not too confusing

**Comment by G1K** [comment]
Writing comments in json is confusing too (
We need a separate config reference.

Most of the device settings are made similar to the general settings, but they are applied more precisely in the context of devices

**"min_rssi"** : -80, // skip advertise with a smaller signal
**"presence_timeout"** : 1, // How many seconds to wait for emitting a presence event, after latest time polled
If you want to exclude some of the data, you can use the settings.
* "exclude_services" // will exclude the service from parsing for example 181a
* "exclude_attributes" // will exclude an attribute like temp
 _For now, I will remove them from the example config_

**"cache_state"**: false // It is necessary for devices transmitting several types of data in one service, for example, temperature, humidity, battery and others. In order for the resulting json to contain all the data known at the last moment, the cache is used. It can be disabled with this setting.

**"bind_key"**: "", // Will be used to decrypt messages, mainly xiaomi

This PR is generic and does not apply to xiaomi devices, but it is necessary for the next one. The common code has been working for several months for me and my colleagues. I just decided to split the changes into small parts.
https://github.com/G1K/EspruinoHub/commits/xiaomi-parser

**Comment by gfwilliams** [comment]
Thanks! That's great! Just merging...

**Pull request merged**
