### PR TITLE
fix github actions

### PR DESCRIPTION
**Pull request by twocolors**
Sorry my mistake.
Fixed branch

test repo https://github.com/twocolors/EspruinoHub/pkgs/container/espruinohub in pi4 , all work and download

```
dietpi@holyland:~$ docker-compose pull
[+] Running 28/28
 ⠿ esphome Pulled                                                                                                                     4.0s
 ⠿ zigbee2mqtt Pulled                                                                                                                32.5s
   ⠿ 47517142f6ba Pull complete                                                                                                       2.1s
   ⠿ 884c28e3c34a Pull complete                                                                                                      12.3s
   ⠿ 78e1e7391210 Pull complete                                                                                                      12.9s
   ⠿ 3ba0e9a671a6 Pull complete                                                                                                      13.1s
   ⠿ 77846ffc5732 Pull complete                                                                                                      13.3s
   ⠿ e92fff306ea3 Pull complete                                                                                                      14.2s
   ⠿ 6f76e58d5a84 Pull complete                                                                                                      26.9s
   ⠿ 2bc72df0a2f0 Pull complete                                                                                                      27.2s
   ⠿ fd5e651c4436 Pull complete                                                                                                      27.3s
   ⠿ 3b16967dae1d Pull complete                                                                                                      27.5s
   ⠿ 03d95005573f Pull complete                                                                                                      27.7s
   ⠿ 63fc86ec2fd1 Pull complete                                                                                                      27.8s
   ⠿ e43a61da9823 Pull complete                                                                                                      28.0s
 ⠿ bitwarden Pulled                                                                                                                   4.0s
 ⠿ node-red Pulled                                                                                                                    4.0s
 ⠿ espruinohub Pulled                                                                                                                27.8s
   ⠿ 9b18e9b68314 Already exists                                                                                                      0.0s
   ⠿ 0d655833cfaa Pull complete                                                                                                      18.5s
   ⠿ 2f08c7b297ae Pull complete                                                                                                      19.2s
   ⠿ 11c4ef253ff7 Pull complete                                                                                                      19.4s
   ⠿ c896c647a1b4 Pull complete                                                                                                      21.3s
   ⠿ 6299999fcb1e Pull complete                                                                                                      21.8s
   ⠿ 4f4fb700ef54 Pull complete                                                                                                      22.0s
 ⠿ mqtt Pulled                                                                                                                       12.8s
   ⠿ c8bc080ce6f7 Pull complete                                                                                                       7.6s
   ⠿ 9335faac8637 Pull complete                                                                                                       7.8s
dietpi@holyland:~$ docker-compose up -d --force-recreate esp
esphome      espruinohub
dietpi@holyland:~$ docker-compose up -d --force-recreate esp
esphome      espruinohub
dietpi@holyland:~$ docker-compose up -d --force-recreate espruinohub
[+] Running 0/1
[+] Running 1/1pruinohub  Recreate                                                                                                    3.0s
 ⠿ Container espruinohub  Started                                                                                                    10.9s
dietpi@holyland:~$
dietpi@holyland:~$ sudo docker-compose logs -f espruinohub --tail=150
espruinohub  | [Config] Config /data/config.json loaded
espruinohub  | [HTTPProxy] config.http_proxy=false, not enabling Bleno/Proxy
espruinohub  | [MQTT] Connecting...
espruinohub  | [HTTP] No http_port in config. Not enabling web server
espruinohub  | [History] history_path value is empty, thus not providing history.
espruinohub  | [MQTT] Connected
espruinohub  | [Discover] Re-sending presence status of known devices
espruinohub  | [Discover] Noble StateChange: poweredOn
espruinohub  | [Discover] caller if function () {
espruinohub  |     exports.startScan();
espruinohub  |   }
espruinohub  | [Discover] Spawning check-broken interval
espruinohub  | [Discover] Starting Scan
espruinohub  | [Discover] Scanning started.
``

### CODE REVIEW

**Comment by gfwilliams** [comment]
Great - thanks!

**Comment by twocolors** [comment]
@gfwilliams plz config package for visible and access more https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility

**Comment by gfwilliams** [comment]
Sorry, but I don't seem to be able to make the package public:

> Setting is disabled by organization administrators

I can't see what's needed to enable this, and I don't have time to figure it out at the moment

**Comment by twocolors** [comment]
This allowed users to download the docker container from 
```
docker pull ghcr.io/espruino/espruinohub
```
But it's all up to you

Thanks

**Comment by jjok** [comment]
Yeah, I don't think anyone has access to the container registry at the moment. Maybe just Gordon.

```
pi@espruinohub:~ $ docker pull ghcr.io/espruino/espruinohub
Using default tag: latest
Error response from daemon: Get https://ghcr.io/v2/espruino/espruinohub/manifests/latest: unauthorized
```

**Comment by twocolors** [comment]
@jjok you can fork and use your or https://github.com/twocolors/EspruinoHub/pkgs/container/espruinohub

**Comment by gfwilliams** [comment]
Maybe try now?

**Comment by jjok** [comment]
Yep, I can pull that now. Thanks.

Although it doesn't seem to work on a Pi 1 (arm32v6/armhf). I'll see if I have have a look why tonight. It's not obvious if the base Node image is meant to be compatible with all the different architectures, or if you're meant to use one the architecture-specific images.

**Comment by jjok** [comment]
OK, I spent a while trying to get it to work with Raspberry Pi OS (Buster) and ended up unbootable. I reinstalled using the latest version (Bullseye), ran the commands in the README and it worked straight away.

Good work everyone. Thanks.

**Pull request merged**
