### PR TITLE
Added mqtt topic prefix configuration option

### PR DESCRIPTION
**Pull request by Arnooooo**
Added MQTT topic configuration option as discussed in #38

### CODE REVIEW

**Comment by gfwilliams** [comment]
Looks great! However I think you might have missed a few instances? For example https://github.com/espruino/EspruinoHub/blob/master/lib/mqttclient.js#L45

**Comment by Arnooooo** [comment]
@gfwilliams Please help me think about what to do with this line: https://github.com/espruino/EspruinoHub/blob/454d9c5d8c260131924361de5d99be6635513023/lib/history.js#L108

**Comment by gfwilliams** [comment]
You mean just in the comment? I'd replace it with `config.history_path+"advertise/"`

**Comment by Arnooooo** [comment]
Yes. I fixed it, so please merge :)

**Comment by gfwilliams** [comment]
Thanks!

**Pull request merged**
