### PR TITLE
Dockerfile

### LINKED ISSUE #16: Image docker ready
Hello Gordon...

Image docker created for quick start...
https://github.com/humbertosales/espruinohub-docker-rpi

### PR DESCRIPTION
**Pull request by jjok**
Closes #16.

This is what I've been running on a Raspberry Pi Zero W with Raspbian/Raspberry Pi OS for the last few weeks.

The idea is that the architecture is a build argument that can be passed in, so you ought to be able to pass in `armv7l` to build on a Pi 3 (or 4?).
The Node version is also an argument at the moment, although maybe we should decide which is the version people should be using.

I'm currently installing all the Bluetooth packages, but I'm not how much of that is required if you run the container with `--net=host`, so it has full access to the host's networking. See https://github.com/espruino/EspruinoHub/issues/16#issuecomment-632806675.

I'll add something like this to the README:

Build container:

    docker build -t espruino/espruinohub:armhf https://github.com/espruino/EspruinoHub.git

Run:

    docker run -d -v $PWD/config.json:/EspruinoHub/config.json:ro --restart=always --net=host --name espruinohub espruino/espruinohub:armhf

The build could even be done by CI on Github, so people can just pull the image and use it without having to build themselves (it takes a pretty long time on a Pi Zero).

### CODE REVIEW

**Comment by gfwilliams** [comment]
Nice! It might actually be that if you're using `NOBLE_HCI_DEVICE_ID=1`/etc then it just need access to the HCI device in `/dev/` and no bluetooth libs at all.

If you think this is good to go I'm happy to merge it, although some docs in the README.md would be great

**Comment by jjok** [comment]
I've just added docs for Pi Zero at the moment, as I haven't tested it on any others. There's an `armv7l` version or Node, and an `arm64`, and I'm not sure if those would be Pi 3 and 4, respectively, so I've just left it for now.

I can't test the `build` command until it's merged, as it points to this repo, but this is the one that I've tested against my branch:

    docker build -t espruino/espruinohub:armhf https://github.com/jjok/EspruinoHub.git#dockerfile

**Comment by jjok** [comment]
I tried removing some of the Bluetooth stuff and I think that was causing some error messages during the `npm install`, so I've just left it as is for now.
I'm sure there are several ways it can be improved / made more flexible (an option to start with a different base image should allow running on x86/x64, for example), but I think this is a good start.

**Comment by gfwilliams** [comment]
This looks great - thank you!

**Pull request merged**
